name: attendance_app
description: تطبيق حضور بالبصمة
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.2.0
  http: ^1.2.2
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true